ansible/requirements.yml

Old master has now been tagged as 2.0.0

Bump haproxy to 2.0.0

---

ansible/group_vars/omero-hosts.yml
ansible/group_vars/proxy-hosts.yml

cc @joshmoore @manics 
if boolean doesnt work we can wrap them in `""`
--depends-on https://github.com/ome/omero-mapr/pull/18

update mapr config to match 0.1.12

---

ansible/group_vars/dockermanager-hosts.yml
ansible/group_vars/omero-hosts.yml
ansible/idr-docker.yml
ansible/idr-dundee-nfs.yml
ansible/requirements.yml

Additional commits on top of https://github.com/IDR/deployment/pull/15, related to going from test35 to demo35
--depends-on https://github.com/IDR/deployment/pull/15

demo35 fixes and jupyterhub config (IDR-0.3.5)

---

README.md
ansible/group_vars/dockermanager-hosts.yml
ansible/group_vars/proxy-hosts.yml
ansible/idr-docker.yml
ansible/openstack-create-infrastructure.yml
ansible/requirements.yml

This will not work until the following are renamed:
- https://github.com/IDR/idr-notebooks/pull/15

Switch from idr-demo to idr (IDR-0.3.6)

---

ansible/group_vars/omero-hosts.yml

List all cell lines when openening category.

all Cell lines should be preset by default

---

ansible/group_vars/omero-hosts.yml

Cell line needs to be plural

---

ansible/group_vars/omero-hosts.yml

* Use downloads.openmicroscopy.org/idr/omero/0.3.7/

Bump to 0.3.7

---

ansible/management-prometheus.yml
ansible/requirements.yml

Opening this to give a preview of what I've done so far.

Prometheus monitoring

---

ansible/management-prometheus.yml
ansible/requirements.yml

This is the same as gh-29 but rebased onto master.
----
Opening this to give a preview of what I've done so far.

Prometheus monitoring (rebased onto master)

---

ansible/group_vars/omero-hosts.yml

Fixes that don't fit into other IDR-0.4.2 PRs

Miscellaneous cleanups (IDR-0.4.2)

---

scripts/os-idr-delete.sh

We've re-architected the IDR with OMERO.readonly and a distributed VAE.

Update delete script with omero cluster and flat net (IDR-0.4.2)

---

ansible/grafana-dashboards/idr-per-server.json
ansible/grafana-dashboards/idr-sessions.json
ansible/grafana-dashboards/idr-vertical.json
ansible/management-grafana.yml
ansible/management-prometheus.yml

Adds Grafana to the management VM, and auto-configures some dashboards.

Add grafana dashboards (IDR-0.4.2)

---

ansible/requirements.yml

See openmicroscopy/ansible-role-jekyll-build#9

Bump jekyll-build version to 1.2.1

---

ansible/group_vars/omero-hosts.yml

See https://trello.com/c/5YxevpeC/86-change-name-of-demo-user
Screenshot on a test system, in conjunction with the other changes in the above trello card:

Change tree head label to "Public data"

---

ansible/decommission/archive-instance-networks.yml
ansible/decommission/archive-instance-services.yml

These playbooks are copied from a private repo.

Add playbooks for archiving old prod IDR (IDR-0.4.4)

---

ansible/idr-ebi-nfs.yml

Minor cleanup- this is already handled elsewhere

Remove nfs group creation (IDR-0.4.4)

---

ansible/management-prometheus.yml

Adds monitoring of Postgres, and some clean-ups.

Prometheus updates (IDR-0.4.4)

---

ansible/experimental-omero-fpbioimage.yml

This is not run by default, and will require more work if we want this in production.

Add experimental-omero-fpbioimage.yml playbook (IDR-0.4.4)

---

ansible/experimental-omero-web-addons.yml

Adds iviewer.
This is not deployed by default, but the playbook is added here for future investigation.

Add more experimental web apps (IDR-0.4.4)

---

ansible/grafana-dashboards/idr-postgresql.json
ansible/idr-09-monitoring.yml
ansible/management-grafana.yml

- Add a dashboard for postgres.
- Always deploy grafana.

Grafana improvements (IDR-0.4.4)

---

ansible/requirements.yml

See also openmicroscopy/prod-playbooks#25 and https://github.com/ome/ansible-examples-omero/pull/10

Bump openmicroscopy.omego to 0.1.1

---

ansible/group_vars/omero-hosts.yml

Including https://github.com/openmicroscopy/openmicroscopy/pull/5638

Deploy release 0.4.5-rc2 of IDR OMERO

---

ansible/files/fluentd-server/fluent.conf.j2

Exclude nginx "a client request body is buffered ... file" alerts (IDR-0.4.5)

---

ansible/grafana-dashboards/idr-sessions.json

Needed to fit in more omeroreadonly servers.
Also change initial display to 1h.

Change min-width of idr-sessions grafana panels (IDR-0.4.6)

---

ansible/openstack-create-infrastructure.yml
scripts/os-idr-delete.sh

Increase number of omeroreadonly from 2 to 4 (IDR-0.4.6)

---

ansible/group_vars/omero-hosts.yml

Contains the required software changes for the idr0040 study import /cc @dominikl

Bump OMERO release to 0.4.6

---

ansible/group_vars/proxy-hosts.yml
ansible/idr-proxy.yml

Redirects mineotaur to a holding page (https://github.com/IDR/idr.openmicroscopy.org/pull/27/) and jupyter to idr-analysis

Redirect apps

---

ansible/group_vars/proxy-hosts.yml

see: https://github.com/IDR/deployment/pull/113
(Manually applied to prod50)

Add .html suffix to mineotaur redirect

---

ansible/openstack-create-ftp.yml

Bump size of FTP volume to 5TB

---

ansible/management-grafana.yml
ansible/management-prometheus.yml
ansible/requirements.yml

Bump all prometheus exporters, prometheus server, and grafana.

Prometheus monitoring bump (IDR-0.5.1)

---

scripts/os-idr-delete.py

Add help/description text based on the description of PR https://github.com/IDR/deployment/pull/102 since this script is now the recommended way to delete IDR resources.

Expand delete script description text

---

ansible/idr-ebi-nfs.yml
ansible/openstack-create-publicidr.yml

See:
- https://trello.com/c/GKEgLjPb/51-request-nfs-biostudies-and-mount

Add configurable NFS mounts for internal read-only access to raw data

---

ansible/group_vars/omero-hosts.yml
ansible/requirements.yml

This should ensure check-mode works with omero-web: https://github.com/openmicroscopy/ansible-role-omero-web/pull/16

Bump omero-web role to 2.0.1

---

ansible/group_vars/omero-hosts.yml

Might be needed for https://github.com/IDR/deployment/pull/133 ?
This has been deployed on test52

Add api/ to omero.web.public_filter

---

ansible/group_vars/omero-hosts.yml

This new release candidate includes an upgrade to IDR Bio-Formats which includes the changes from Bio-Formats 5.9.2 as well as a new reader (KLB) and improvements to readers (Operetta, OME-TIFF) used in submissions.

Bump IDR OMERO release to 0.6.0-rc1

---

ansible/decommission/archive-logs.yml

These errors were discovered whilst running the playbook today on prod51: https://trello.com/c/Jww9YsQ0/12-archive-logs

Fix variable errors in archive logs msg

---

ansible/decommission/archive-db.yml
ansible/decommission/group_vars

Another decommissioning playbook to take a dump of the database. Requires Ansible 2.4
Used in https://trello.com/c/oEOqeKgR/31-re-snapshot-db

Ansible playbook to dump postgres DB

---

ansible/group_vars/omero-hosts.yml

Separate PR so it's easy to revert if necessary.

Make iviewer the default image viewer

---

ansible/group_vars/omero-hosts.yml

Based on latest config in https://github.com/ome/omero-iviewer/blob/v0.6.0/plugin/omero_iviewer/README.rst

Add dataset and well to iviewer

---

ansible/group_vars/proxy-hosts.yml

Update website to 2018.12.20 (prod61)

---

ansible/group_vars/proxy-hosts.yml

Update website and stats to 2019.01.16

---

ansible/requirements.yml

Required for https://github.com/IDR/idr0052-walther-condensinmap/pull/8

Bump openmicroscopy.python-pydata to 1.1.0

---

ansible/group_vars/proxy-hosts.yml

Update website 2019.04.11

---

docs/operating-procedures.md

fix minor typo

---

ansible/group_vars/proxy-hosts.yml

Bump website to 2019.06.06

---

ansible/group_vars/omero-hosts.yml

To allow testing of https://github.com/ome/omero-mapr/pull/46 with https://github.com/ome/omero-gallery/pull/25

Bump mapr to 0.3.0a1, install gallery

---

ansible/files/patches/pr6046-omeroweb-urls.patch
ansible/group_vars/proxy-hosts.yml
ansible/idr-omero-web.yml

~/ ➜ /gallery
/cell ➜ /gallery/cell
/tissue ➜ /gallery/tissue~
`/` is now the gallery app

Gallery is the idr root

---

ansible/group_vars/omero-hosts.yml
ansible/group_vars/proxy-hosts.yml

The latest released OMERO.gallery and IDR static content.

OMERO.gallery 3.2.0a6, Website 2019.06.11

---

ansible/var-overrides/omero-ci-build.yml

Tested during the redeployment of `test70`

Update the location of the idr-ci Jenkins server

---

ansible/group_vars/omero-hosts.yml

This should included the fix for reading screenD of the idr0011 study

Bump IDR Bio-Formats release to 0.6.1

---

ansible/molecule/publicidr/molecule.yml
ansible/requirements.yml

See https://github.com/ome/omero-install/issues/212

PSQL temporary fix revert

---

ansible/group_vars/omero-hosts.yml

bump iviewer version to 0.8.1
cc @sbesson

iviewer 0.8.1

---

ansible/group_vars/proxy-hosts.yml
scripts/os-idr-snapshot.sh
scripts/os-idr-swapip.py

prod71 website update and release script fixes

---

ansible/group_vars/omero-hosts.yml

It must've gone missing at some point in the past...

Set the top-left webclient logo

---

ansible/group_vars/omero-hosts.yml

Add new menu for map annotation with openmicroscopy.org/mapr/protein
namespace

Add new Protein mapr category

---

ansible/group_vars/proxy-hosts.yml
ansible/production-tests/test_web.py

- remove custom redirect to the download page for idr0065
- TBD: update idr.openmicroscopy.org with updated stats

Final prod72 adjustmenets

---

ansible/group_vars/proxy-hosts.yml

DO NOT MERGE YET
In preparation of the Aspera as per last point of the https://docs.google.com/document/d/1TmBZ43_yhiO3AOua8oMk4mPWKWJtpeYNc2KLP17h-1I/edit#heading=h.y7esxztmffg8
The link to Aspera has not been finalized yet, this is just a draft.
cc @sbesson @manics

Add redirect for idr0048 to downloads

---

ansible/group_vars/proxy-hosts.yml

Update with https://github.com/IDR/idr.openmicroscopy.org/pull/81

Stats for idr0064 idr0083

---

docs/operating-procedures.md

Small tweaks to suggested shell commands, see diff.

Adjust shell commands for memo regeneration for Bio-Formats.

---

ansible/group_vars/omero-hosts.yml
ansible/group_vars/proxy-hosts.yml

Also update gallery top-right links to match

Update website to version 2020.06.29 including FAQ

---

ansible/group_vars/proxy-hosts.yml

Update website for prod84

---

ansible/group_vars/omero-hosts.yml

See https://github.com/ome/omero-py/blob/v5.7.1/CHANGELOG.md for the corresponding changes
Target: `prod85`

Bump omero-py version to 5.7.1

---

ansible/group_vars/proxy-hosts.yml

Update static website for upcoming prod85 release

---

ansible/group_vars/omero-hosts.yml
ansible/requirements.yml

Depends on ome/ansible-role-omero-user#4

Test ome.omero_user role changing the default value of omero_user_bin_omero

---

ansible/files/idrftp/idrftp-aspera-sh.j2
ansible/idr-ftp.yml

Installs cli-utils and rclone.

FTP and file transfer command line utils

---

ansible/group_vars/omero-hosts.yml

See https://github.com/ome/omero-cli-render/blob/v0.6.0/CHANGES.md for the list of changes

Bump omero-cli-render to version 0.6.0

---

ansible/requirements.yml

Needed for the prod86 full deployment

ansible role: ome.munin 1.1.3-openmicroscopy2

---

ansible/idr-01-install-idr.yml
ansible/idr-s3gateway.yml
ansible/openstack-create-ftp.yml
ansible/requirements.yml

Add S3 gateway to idr-ftp

---

ansible/group_vars/omero-hosts.yml

bump omero-gallery to 3.3.3

---

ansible/group_vars/proxy-hosts.yml

This data should be made available via Aspera imminently

Redirect idr0095 to downloads page

---

ansible/group_vars/proxy-hosts.yml

In preparation of the final checks, removes the top-level redirect to the downloads page

Remove redirect for idr0078

---

ansible/group_vars/proxy-hosts.yml

See https://github.com/IDR/idr.openmicroscopy.org/compare/2020.09.03...2020.09.28 for the list of changes.
Primarily stats additions for `prod88`

Update static website

---

ansible/group_vars/proxy-hosts.yml

This configuration is unused, everything can be done using port 9000

Remove unused omeroreadwrite:8009 proxy

---

ansible/group_vars/omero-hosts.yml

Includes https://github.com/ome/omero-mapr/pull/63

Bump omero-mapr to version 0.4.1

---

ansible/group_vars/proxy-hosts.yml

This study is scheduled for publication in `prod89`

Remove idr0094 redirect

---

ansible/group_vars/proxy-hosts.yml
ansible/requirements.yml

See https://github.com/ome/ansible-role-nginx-proxy/pull/29

Block non-websocket connections to OMERO.server

---

ansible/group_vars/proxy-hosts.yml

Final location is still to be decided

Redirect /curation-workflow

---

ansible/openstack-create-infrastructure.yml
ansible/openstack-create-pilotidr-servers.yml

New NGFF Zarr dev server at EBI

pilot deployment can have a docker dev server

---

ansible/group_vars/omero-hosts.yml

Deploys the the bug fix for the file handles from https://github.com/IDR/bioformats/pull/23

Use 0.6.5 version of IDR Bio-Formats components

---

ansible/group_vars/proxy-hosts.yml

Website 2020.12.09

---

ansible/group_vars/omero-hosts.yml

Includes https://github.com/ome/omero-metadata/pull/52

Update omero-metadata to 0.7.0

---

README.md
docs/idr-ftp-s3.md
docs/idr-s3.md

Add a short doc about the idr-ftp S3 Minio upload server

Add idr-s3 docs

---

ansible/group_vars/omero-hosts.yml

This should include support for setting min/max values using the rendering plugin in future deployments of the IDR instance
/cc @pwalczysko @will-moore

Bump omero-cli-render to version 0.7.0

---

ansible/group_vars/proxy-hosts.yml

Website 2021.01.27

---

docs/monitoring.md

Adds a bit more information to the IDR monitoring docs.

Update monitoring docs

---

ansible/group_vars/omero-hosts.yml

Add configuration for notebook
needed for idr0093

Add notebook config

---

ansible/group_vars/proxy-hosts.yml

This study is part of the upcoming `prod94` roadmap

Remove top-level idr0090 redirect

---

ansible/group_vars/proxy-hosts.yml

In preparation of the release of `prod95`

Bump IDR static website

---

ansible/group_vars/omero-hosts.yml
ansible/requirements.yml

Also remove deprecated ome.omego and ome.omero_python_deps roles

Consume latest released ome.omero_server and ome.omero_web roles

---

ansible/group_vars/proxy-hosts.yml

Includes stats for `idr0063` and `idr0072`

Deploy latest version of IDR website

---

ansible/group_vars/omero-hosts.yml

Includes the fix for `idr0110`

Update IDR Bio-Formats version to 0.6.7

---

ansible/openstack-create-pilotidr-servers.yml

This should allow to process some of the largest individual volumes published in IDR

Increase pilot dev server volume size to 5000G

---

ansible/group_vars/omero-hosts.yml
ansible/group_vars/proxy-hosts.yml

Linked resources

---

ansible/group_vars/omero-hosts.yml

This release needed for idr0123

Bump OMERO.web release to 5.13.0

---

ansible/group_vars/omero-hosts.yml

Bump idr-gallery 3.6.0

---

ansible/group_vars/omero-hosts.yml
ansible/group_vars/proxy-hosts.yml

Includes the latest website changes as well as the new idr-gallery app with the video updates

Prod106 updates

---

ansible/group_vars/omero-hosts.yml

In order to deploy latest change in https://github.com/IDR/idr-gallery/pull/10

bump idr-gallery to 3.6.2

---

ansible/group_vars/omero-hosts.yml

bump idr-gallery to 3.7.1

---

inventories/openstack-idr.py

Fix error when running playbook with Python 3.9
cc @pwalczysko

use packaging

---

ansible/group_vars/searchengine-hosts.yml

I have updated `searchengine-hosts.yml` with the new searchengine version.

change searchEngine version to 0.5.0

---

ansible/group_vars/omero-hosts.yml

Bump idr-gallery to 3.9.0

---

ansible/group_vars/omero-hosts.yml

Bump idr-gallery to 3.9.1

---

ansible/requirements.yml

bump ome.omero_server to 4.1.0

bump ome.omero_server to 4.1.0

---

ansible/group_vars/omero-hosts.yml

bump omero-web to latest release

bump omero-web 5.21.0

---

ansible/group_vars/searchengine-hosts.yml

Update the search engine version to 0.5.2.

update searchengine version

---

ansible/group_vars/omero-hosts.yml

Bump to 3.10.1: version removing twitter feed

bump idr-gallery to 3.10.1

---

ansible/group_vars/omero-hosts.yml

Addresses issues with mapr-based auto-complete on front page, particularly for Cell Line.
cc @sbesson

bump idr-gallery 3.11.0

---

ansible/group_vars/proxy-hosts.yml

Add a download page redirect for idr0138 and idr0158.

Add redirects for idr0138 and idro0158

---

ansible/decommission/archive-instance-services.yml
ansible/group_vars/database-hosts.yml
ansible/group_vars/omero-hosts.yml
ansible/molecule/publicidr/tests/test_database.py

Upgrade to use PostgreSQL 16

---

.github/workflows/molecule.yml

This PR capps the version of requests to fix the requests 2.32.0 issue. 
cc @will-moore

Fix requests 2.32.0 issue

---

ansible/group_vars/omero-hosts.yml

See https://www.openmicroscopy.org/2024/08/15/omero-5-6-13.html
No functional change, this is primarily a tidy-up

Bump OMERO.server to version 5.6.13

---

ansible/group_vars/omero-hosts.yml

Add OMAP mapr category

---

ansible/group_vars/proxy-hosts.yml

See title. I just commented it out, might be handy to have it for other/future redirects. 
/cc @sbesson 
Bit worried to apply that on idr-next... would it overwrite other configs (e.g. nginx) again!?

Comment out idr0158 redirect

---

ansible/group_vars/omero-hosts.yml
ansible/idr-omero-readonly.yml
ansible/idr-omero.yml

See Title. I'll try to spin up a pilot with these changes for testing.
/cc @sbesson

Add omero-zarr-pixel-buffer to deployment

---

ansible/openstack-create-publicidr.yml
scripts/os-idr-snapshot.sh

Fix volume name for searchengine backup
