IDR/deployment

- ansible/idr-omero.yml
- ansible/idr-proxy.yml
- ansible/molecule.yml
- ansible/openstack-create-infrastructure.yml
- ansible/requirements.yml
Some minor fixes discovered whilst writing the standalone deployment docs. The most significant change is defaulting to Nginx self-signed SSL certificates- without this Nginx will fail to start due to missing certificates. This won't affect production deployments because they define `idr_nginx_ssl_production: True`
> Minor playbook fixes

- .travis.yml
- ansible/requirements.yml
- ansible/tests/python-requirements.txt
Bump requirements.
Test `idr-01-install-idr.yml` applied to `idr-database`, `idr-omero`, `idr-proxy` with travis in Docker. The other main deployment playbooks and servers (such as the analysis servers) aren't tested. This corresponds to the main public production IDR.
> Travis test idr-01-install-idr.yml

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/idr-downloads.yml
- ansible/idr-proxy.yml
- ansible/requirements.yml
* Similar to the forwarding of `/jupyter` to a container on the dockermanager host, this forwards `/mineotaur` to another container on port 8080.
* Permit rsync'ing from /data/OMERO/mineotaur on the omero host
* Open rsync on the proxy host
> 0.3.4: Add mineotaur, rsync support, etc

- ansible/files/idr-rsync-backup.sh
`bin/omero` no longer looks to be on the user's
PATH. This uses the absolute paths.
> rsync: update script to match new deployment

- ansible/idr-01-install-idr.yml
- ansible/idr-02-services.yml
- ansible/idr-mineotaur.yml
* rsync from the production
* initial work for rsync'ing from `omero_omero` host
* use the hard-coded sysgro subdir
> mineotaur: enable deployment (IDR-0.3.6)

- ansible/idr-dundee-nfs.yml
The NFS mount should be `/uod/idr`
In the future the `idr-*-nfs.yml` playbooks should be refactored into a single playbook, with variables in group-vars.
> Fix uod nfs mount

- ansible/group_vars/dockermanager-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/requirements.yml
See:
- https://trello.com/c/QPUQBShK/23-github-org-oauth-seems-to-let-everyone-in
- https://trello.com/c/0SacUNN6/24-update-all-jupyterhub-components
> Run JupyterHub 0.7.2 directly

- ansible/group_vars/omero-hosts.yml
See https://trello.com/c/s22IQBKY/26-increase-gunicorn-workers
OMERO.web and OMERO.server are currently on the same VM. In the event this change to the number of wsgi-workers causes problems revert it.
> Set omero.web.wsgi_workers: 25 (IDR-0.3.7)

- ansible/production-tests/test_web.py
Simple tests of public IDR URLs. Some of the tests require an existing IDR production database, and will fail on a new empty IDR. These should not be confused with the molecule tests under `tests/`.
```
$ pytest -vs production-tests/
============================= test session starts ==============================
plugins: testinfra-1.5.5
collected 6 items
production-tests/test_web.py::test_about_redirect[-/about] PASSED
production-tests/test_web.py::test_about_redirect[/about-/about/] PASSED
production-tests/test_web.py::test_about_get[/about/-The IDR makes datasets that have never previously been] PASSED
production-tests/test_web.py::test_about_get[/about/experiments.html-When submitting data to the IDR, you] PASSED
production-tests/test_web.py::test_mapr_organism_count PASSED …
```
> [RFC] Initial smoketests for the production IDR public web

- scripts/os-idr-delete.sh
- scripts/os-idr-snapshot.sh
- scripts/os-idr-snapshot2image.sh
Adds copies of the main openstack IDR scripts which are currently in several different repositories:
- `os-idr-delete.sh`: Deletes everything in a given IDR environment
- `os-idr-snapshot.sh`: Snapshots important instances and volumes
- `os-idr-snapshot2image.sh`: Converts a volume snapshot into an image for transfer between clouds. Always seems to time out but in theory this should work.
> Openstack snapshot and delete scripts (IDR-0.4.0)

- ansible/molecule-playbook.yml
- ansible/requirements.yml
This is a workaround to get molecule/travis passing on master.
Follow-up on https://trello.com/c/9KkfveSV/64-refactor-rsyslog-in-openmicroscopyhaproxy
> Temporary workaround for rsyslog molecule/travis failure

- scripts/os-idr-swapip.py
Assign an unallocated floating IP (dry-run)
```
$ ./os-idr-swapip.py uodtest-proxy 10.0.51.110
Detaching IP 10.0.51.112 from uodtest-proxy (192.168.1.7)
Attaching IP 10.0.51.110 to uodtest-proxy (192.168.1.7)
Enter "yes" to continue with these changes
(have you snapshotted the instances and volumes?):
Aborting
```
Assign an unallocated floating IP:
```
$ ./os-idr-swapip.py uodtest-proxy 10.0.51.110
Detaching IP 10.0.51.112 from uodtest-proxy (192.168.1.7)
Attaching IP 10.0.51.110 to uodtest-proxy (192.168.1.7)
Enter "yes" to continue with these changes
(have you snapshotted the instances and volumes?): yes
Detaching IP 10.0.51.112 from uodtest-proxy (192.168.1.7)
Attaching IP 10.0.51.110 to uodtest-proxy (192.168.1.7)
```
Assign a floating IP allocated to another server:
```
$ …
```
> Add script for swapping floating IPs when releasing a new IDR version

- ansible/decommission/archive-logs.yml
E.g.
```
PLAY [uodtest-proxy-hosts uodtest-management-hosts] ****************************
TASK [Gathering Facts] *********************************************************
ok: [e3f02fa1-06e4-42f7-9991-ad3d772affde]
ok: [65b6b7ec-ae81-4d2e-a0db-b9342af0c9b9]
TASK [Get archive prefix] ******************************************************
ok: [e3f02fa1-06e4-42f7-9991-ad3d772affde]
ok: [65b6b7ec-ae81-4d2e-a0db-b9342af0c9b9]
PLAY [uodtest-proxy-hosts] *****************************************************
TASK [Archive proxy nginx logs] ************************************************
changed: [e3f02fa1-06e4-42f7-9991-ad3d772affde]
TASK [Fetch proxy nginx logs archive] ******************************************
changed: [e3f02fa1-06e4-42f7-9991-ad3d772affde]
TASK [Print archive information] …
```
> Add playbook for archiving nginx and munin logs

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-omero.yml
- Increases the timeout in omeroreadwrite's OMERO.web nginx.conf
- In future this should be replaced by a template that takes advantage of https://github.com/openmicroscopy/openmicroscopy/pull/5387
Note Nginx proxy changes are also present in https://github.com/IDR/deployment/pull/36
> Front-end proxy (IDR-0.4.2)

- ansible/group_vars/omero-hosts.yml
- ansible/idr-omero.yml
Changes made as a response to failures in release testing: https://trello.com/c/isuehtZ6/78-release-testing-failures
- Uses a separate Redis server for each OMERO.web instance. This shouldn't be necessary but was done to rule out as many potential issues as possible, it may be reverted in future.
- Enables the little known never tested `omero.web.public.cache.enabled` option. See https://trello.com/c/Di7IgStr/80-omerowebpubliccacheenabled and linked conversations
> OMERO.web performance/errors (IDR-0.4.2)

- ansible/management.yml
This changes the destination channels:
- `idr-notify` to `idr-notify-XXX` (munin notifications)
- `idr-logs` to `idr-logs-XXX` (OMERO server/web error logs)
- `idr-deployment` to `idr-logs-XXX` (docker notifications)
> Send slack messages to per-deployment channels (IDR-0.4.2)

- ansible/idr-omero-readonly.yml
The idr-metadata directory is intrinsically linked to the OMERO ManagedRepository, so the read-only servers should use the read-write server's copy.
> Use a shared OMERO idr-metadata directory (IDR-0.4.2)

- ansible/group_vars/dockermanager-hosts.yml
- ansible/group_vars/dockerworker-hosts.yml
- ansible/idr-kubernetes.yml
- ansible/roles/kubernetes/defaults/main.yml
- ansible/roles/kubernetes/tasks/common.yml
An error was introduced in kubeadm 1.7.1: https://github.com/kubernetes/kubeadm/issues/347
This pins the Kubernetes version to 1.7.0 until it's fixed in an upstream release.
> Pin Kubernetes/kubeadm version (IDR-0.4.2)

- ansible/group_vars/proxy-hosts.yml
- ansible/management-prometheus.yml
- ansible/requirements.yml
Adds more Prometheus monitoring, some of which was used to investigate performance problems in the openmicroscopy `metadata53`branch:
- Installs a custom version of `django_prometheus`
- Changes were made to `django_prometheus` to work with multi-process wsgi/gunicorn (the alternative was code changes to OMERO.web)
- Subsequently someone has opened an upstream PR with the same functionality: https://github.com/korfuri/django-prometheus/pull/46 so we can revert to upstream when it's released
- Re-enables the jmx-exporter, using a custom build
- The problems we had with the jmx-exporter should be fixed by https://github.com/prometheus/jmx_exporter/pull/162 so I made a devel build to test this: https://github.com/openmicroscopy/ansible-role-prometheus-jmx/pull/1
- Subsequently there was an …
> More prometheus monitoring (IDR-0.4.2)

- ansible/roles/kubernetes/tasks/master.yml
An upstream change broke something. The longer term plan is to move to Kubespray for deploying ansible instead of maintaining our own role.
> Pin version of flannel playbook in roles/kubernetes (IDR-0.4.4)

- scripts/os-idr-delete.sh
- scripts/os-idr-snapshot.sh
Everything is now in a single network. This also adds a warning to the delete script when deleting non-test deployments.
> Update scripts for latest deployment structure (IDR-0.4.4)

- ansible/idr-00-preinstall.yml
- ansible/idr-centos-init.yml
The CentOS 7 cloud image default to not keeping logs over a reboot. See https://unix.stackexchange.com/a/159390
> Ensure journald logs are maintained after a reboot (IDR-0.4.4)

- ansible/group_vars/dockermanager-hosts.yml
- ansible/group_vars/dockerworker-hosts.yml
- ansible/idr-docker.yml
- ansible/idr-kubernetes-apply.yml
- ansible/idr-kubernetes.yml
Removes notebooks from the docker hosts- this is now handled inside the `imagedata/jupyter-docker` notebook image.
> Docker/kubernetes host deployment (IDR-0.4.4)

- ansible/group_vars/database-hosts.yml
- ansible/group_vars/omero-hosts.yml
- ansible/idr-01-install-idr.yml
- ansible/idr-omero-readonly.yml
- ansible/idr-omero-web.yml
- ansible/idr-omero.yml
- ansible/idr-reset-users-groups.yml
- ansible/requirements.yml
Additional cleanups include moving omero-web into a separate playbook
~~--depends-on https://github.com/IDR/deployment/pull/62~~ Commits from https://github.com/IDR/deployment/pull/62 are now included here
> Bump OMERO, update PG config (IDR-0.4.4)

- ansible/var-overrides/omero-ci-build.yml
Pass `-e @var-overrides/omero-ci-build.yml` to the `ansibile-playbook` deployment script to upgrade to a idr-ci build
--depends-on https://github.com/openmicroscopy/prod-playbooks/pull/28
> Add vars file for upgrading to idr-ci OMERO-build

- ansible/group_vars/omero-hosts.yml
Our docs currently mention `omero.web.application_server.max_requests 500` without any explanation of why, or how to decide: https://docs.openmicroscopy.org/omero/5.4.0/sysadmins/unix/install-web/web-deployment.html#gunicorn-configuration
A slack discussion suggested it's not needed https://openmicroscopy.slack.com/archives/C0K5EED3R/p1507894075000132
Cards on our sysadmin board suggest web needs regular restarts: https://trello.com/c/DC5CB4Ty/34-bug-omeroweb-processes-threads
This increases the limit from 300 to 30000 in the hope that it's not really needed so having a large value won't matter, but that it's low enough so that if there are problems web workers will be restarted before they occur.
Related card:
- https://trello.com/c/n6JhjbPu/17-poor-performance-with-django-prometheus-afte …
> Increase application_server.max_requests from 300 to 30000 (IDR-0.4.5)

- ansible/group_vars/all.yml
- ansible/requirements.yml
During future maintenance we may want to upgrade distro packages. This adds a configuration to prevent `docker*` and `kube*` packages being upgraded. With this in place it _should_ be safe to run all playbooks (against an existing production deployment.
> Exclude docker* kube* from yum upgrades (IDR-0.4.5)

- ansible/files/fluentd-server/fluent.conf.j2
- ansible/files/fluentd/forward-conf.j2
- ansible/files/fluentd/nginx-proxy-conf.j2
- ansible/files/fluentd/nginx-proxy.conf
- ansible/files/fluentd/omero.conf
- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/idr-09-monitoring.yml
- ansible/management-fluentd.yml
- ansible/requirements.yml
~Currently alerts are sent from the monitored node, eventually this will be changed so logs are aggregated and alerts are sent from the central management node.~
Initial work on centralised logging and alerting:
- Central fluentd server for receiving logs and sending Slack alerts
- Agent on idr-proxy to transfer nginx `*.log`
- Agent on idr-omero* to transfer OMERO.server and OMERO.web `*.log` `*.err` `*.out`
Caveats:
- An obvious extension of this work is to process other logs such as haproxy
- Elasticsearch and Kibana are currently unauthenticated (anyone inside the IDR network can access and modify them)
- Elasticsearch configuration (e.g. dashboards) will not be saved between deployments
- In future we could consider whether the configs can be reused outside the IDR, though this can …
> Add fluentd centralised logging (part 1)

- ansible/group_vars/dockerworker-hosts.yml
- ansible/group_vars/omero-hosts.yml
- ansible/requirements.yml
- Bumps IDR OMERO to 0.4.5 (no change since rc2, drops the suffix)
- Bumps the Jupyter Docker image to 0.6.0 (to be created)
> Final version bumps prior to IDR release

- ansible/idr-mineotaur.yml
This rsync was adjusted in #77 to prevent timeouts. However, this results in a `Connection refused`  error as only the readwrite hosts are currently set up for the rsync.
This PR adjusts the default rsync URL. 
Should be tested by the deployment of `test46`
> Fix host used for rsyncing the Mineotaur data

- ansible/group_vars/omero-hosts.yml
The latest release of `django-redis 1.9.0` drops support for Django< 1.11 causing Travis and probably any new deployment of IDR due to the semantics of the requirements file in the current version of `omero-mapr`. 
This PR proposes to bump `omero-mapr` to the latest patch release fixing this issue. Travis is expected to pass with these changes.
The changes made to `omero-mapr` since `0.1.14` were mostly about documentation or testing, so this bump should have no impact on production - see the [0.2.0](https://github.com/ome/omero-mapr/milestone/16) and [0.2.1](https://github.com/ome/omero-mapr/milestone/17) milestones
--depends-on https://github.com/ome/omero-mapr/pull/33
> omero-mapr version bump

- ansible/requirements.yml
Uses dev version of openstack-idr-security-groups
Security groups are shared so this will open up ports for all deployments
> Open additional external ports for OMERO (IDR-0.4.6)

- ansible/idr-mineotaur.yml
With Ansible 2.4.3.0, this change was necessary to run the playbook. Without
it, the download task fails with an error of type
`sudo: unknown user: 1000\r\nsudo: unable to initialize policy plugin\r\n`
> Use centos username rather than id

- ansible/group_vars/dockerworker-hosts.yml
- ansible/idr-docker.yml
- ansible/idr-kubernetes.yml
- Bump docker image prepull to [`imagedata/jupyter-docker:0.7.0`](https://github.com/IDR/jupyter-docker/pull/25)
- Move the prepull task to idr-kubernetes instead of docker since it's related to the application deployment, not the underlying docker infrastructure.
> Bump jupyter-docker image, move docker pull task (IDR-0.4.6)

- ansible/idr-haproxy.yml
- ansible/requirements.yml
- ansible/templates/haproxy.cfg.j2
This directs the incoming TCP connection logs to a separate file `/var/log/haproxy/haproxy-tcp.log`. A few non-connection logs will still creep in but these can be ignored.
> Haproxy separate TCP logs (IDR-0.4.7)

- ansible/roles/kubernetes/defaults/main.yml
- ansible/roles/kubernetes/tasks/worker.yml
@joshmoore ran into a problem where a node couldn't join itself due to a mismatch between hostnames, despite this having worked fine for @sbesson during the last deployment.
> Force hostname in kubeadm init/join

- scripts/os-idr-delete.py
With the latest changes it is impractical to hard code the list of resources that should be deleted, which is made worse by hidden dependencies (e.g. snapshots prevent volumes from being deleted).
This python script uses the `shade` module to find resources that should be deleted. A type parameter allows deletions to be restricted to `server`, `volume` (includes snapshots), `network` (includes routers and subnets), `secgroup` (Security groups and rules), or `all`. A final confirmation is required after the resources to be listed are printed out.
```
$ ./os-idr-delete.py testk8s -t all
Deleting Servers
server testk8s-k8sproxy (6e317900-10e5-4c6a-80ed-a84391bda5ae)
server testk8s-train-node (4c5f75a0-dbdd-4cbe-b844-cecf66bcd19d)
server testk8s-train-master …
```
> Add new delete script that dynamically finds resources

- ansible/group_vars/omero-hosts.yml
To workaround an off-by-one issue in a project with
200 datasets, we're temporarily upping the page size to 500.
see also: https://github.com/openmicroscopy/openmicroscopy/pull/5701
> Bump page_limit to 500

- ansible/files/docker-1.13-kube-1.7.4-iptables.service
- ansible/idr-kubernetes.yml
Since these servers will go away in the next release this is a quick fix.
> Workaround for incompatibilty between Docker 1.13.1 and Kubernetes 1.7.4

- ansible/group_vars/omero-hosts.yml
This is an emergency release of OMERO to fix
failing pip installations of omero-marshal.
see: https://github.com/openmicroscopy/omero-marshal/pull/50
> Bump to OMERO 0.4.7

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy.yml
- ansible/requirements.yml
Use ~~https://github.com/openmicroscopy/ansible-role-nginx-ssl-selfsigned/pull/1~~ https://github.com/openmicroscopy/ansible-role-ssl-certificate to remove the requirement for a local on-disk copy of private SSL https certs.
Closes https://github.com/IDR/deployment/issues/94
> Ssl web certs new role

- ansible/idr-centos-init.yml
When journald starts it resets the permissions on `/var/log/journal`. This PR ensures the perms set by ansible match those set by journald to avoid idempotence warnings when rerunning after journald has been restarted for other reasons.
> Minor idempotence correction for journald dir

- ansible/idr-00-preinstall.yml
This reduces but does not eliminate some long standing issues with race conditions during reboots. The original aim of this repository was to support a full deployment run-through from scratch, with reboots postponed to the very end. In practice this causes problems when installed services are unnecessarily interrupted, or when a service is installed against an old running kernel which changes after the reboot. Instead this PRs executes the reboot at the end of the pre-install stage, after system packages have been upgraded but before any applications are installed.
This will lead to the first full run-through failing after the preinstall stage since the combination of multiple VM reboots via a proxy and rebooting the proxy makes it too complicated to auto-detect when all VMs have …
> Auto-reboot if kernel upgraded immediately after idr-00-preinstall.yml

- ansible/group_vars/proxy-hosts.yml
This blocks the OMERO.web login page on the front-end proxy to prevent private state from being cached. See https://github.com/IDR/deployment/pull/110#discussion_r183026496
> Block proxy /webclient/login

- ansible/openstack-create-publicidr.yml
We're generating a lot of logs and metrics (or there's a misconfiguration which means the  elasticsearch logs aren't being deleted after 14 days). This should ensure they're stored on a 100GB volume instead of in the root partition.
https://trello.com/c/PmYJjRO1/45-make-idr-management-data-into-a-volume
Untested.
> Make idr-management:/data into a volume (IDR-0.5.1)

- ansible/openstack-create-ftp.yml
Follow-up of #117, this addition was used when recreating the IDR FTP service to match the recent extension of the volume.
The default is bumped to 15TB and a new `idr_environment_ftp_size` variable is added to override it via Ansible variables. Alternatively, we could set a much smaller default in the public playbook e.g. 100GB and move the production idr-ftp value to the host variable.
> Update default FTP size and allow it to be configurable

- ansible/group_vars/proxy-hosts.yml
This allows access to the prometheus federation endpoint.
To be decided:
> Allow access to prometheus federation endpoint (currently no auth) (IDR-0.5.1)

- ansible/idr-proxy.yml
The rsync data source is only on the read-write omero server.
> rsync download is on omeroreadwrite host

- ansible/requirements.yml
As discussed earlier, the goal is to test the external changes proposed in https://github.com/openmicroscopy/ansible-role-haproxy/pull/12 against a complete deployment (`test51`)
> Update requirements.yml to consume haproxy 3.1.0

- ansible/tests/test_proxy.py
Fixes a long standing error (testing the wrong server).
Also adds a basic test to ensure the web page is correct.
@sbesson It'd be worth getting this in before the new idr website deployment change.
> Improve idr-proxy web test

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy-about.yml
- ansible/requirements.yml
Replace jekyll build with a pre-built artefact containing the IDR `/about` pages.
Due to the changes required in https://github.com/IDR/idr.openmicroscopy.org this is currently using a temporary build http://users.openmicroscopy.org.uk/~spli/idr/idr-www-test/idr.openmicroscopy.org.tar.gz
Before deploying this manually run `cd /srv/www; sudo mv html html.old && sudo ln -s html.old html`
> Use new deploy_archive role for deploying idr website

- ansible/group_vars/database-hosts.yml
- ansible/requirements.yml
See https://trello.com/b/AM7jhXRQ/idr-051
As tested during the IDR 0.5.0 by @mtbc, this PR bumps the value of `shared_buffers` to 1GB using the `postgresql_server_conf` dictionary. Additionally it bumps `openmicroscopy.postgresql` to the latest version of the role. This should be harmless as there has been no change in the logic in the role, only documentation - see https://github.com/openmicroscopy/ansible-role-postgresql/compare/3.0.0-m2...3.0.1.
> Shared buffers bump

- ansible/requirements.yml
We seem to be lagging behind a bit.
Working on the assumption that we're correctly using semver only the following need to be reviewed:
> Bump all Ansible roles to latest release

- ansible/group_vars/omero-hosts.yml
This PR contains OMERO.server changes for `test52`:
- 8895f22 bumps the version of OMERO to use `0.5.1-rc1` which includes  the 5.4.8-rc1 tag of OMERO with all the parallel import features  - see https://trello.com/c/i0JAPzgB/13-omero-548-rc1
-  1452eed and 164c846 increase the height and the width of the maximum plane size to import the first run of HPA data - see https://trello.com/c/gBAAQTIY/47-hpa-run-1-idr0043
- 4c4c25b updates `omero.fs.repo.path` to contend with parallel imports using the `-%hash` suffix
> test52: OMERO.server changes

- ansible/group_vars/omero-hosts.yml
- ansible/requirements.yml
See https://trello.com/c/EpmQzvoy/2-json-api-publicly-accessible-with-cors
Trying to add CORS support as described at https://docs.openmicroscopy.org/omero/5.4.7/sysadmins/unix/install-web.html#setting-up-cors
Not sure I quite understand how to perform these append steps:
```
$ bin/omero config append omero.web.middleware '{"index": 0.5, "class": "corsheaders.middleware.CorsMiddleware"}'
$ bin/omero config append omero.web.middleware '{"index": 10, "class": "corsheaders.middleware.CorsPostCsrfMiddleware"}'
```
since all the other configs seem to be "set" but I uncommented out the ```omero_web_apps_config_append``` and added yml there which I hope will be appended as JSON, but I don't really know if/how this works or how to test it.
cc @manics @sbesson
> Install and config for django-cors-headers

- ansible/group_vars/omero-hosts.yml
The only difference with b8e4b155ad4fcca0027fd1ce6a4bb9faa50c189f are the last set of PRs included in the public release of OMERO 5.4.8 (see https://github.com/openmicroscopy/openmicroscopy/pull/5872). This should not have any impact in the case of IDR but reduces the delta between the IDR version of OMERO and mainline OMERO to its current minimum.
> Bump to IDR OMERO 0.5.2

- ansible/idr-proxy.yml
- ansible/requirements.yml
This also reverts `openmicroscopy.nginx-proxy` role to `1.7.0` to ensure the Nginx log format is identical to the existing production (prod51) format. Longer term we either need to modify the role to a support the IDR's log format, or update all our log analytics tools to accept both formats.
> Auto-restart after SSL update, revert to previous Nginx logging format

- ansible/experimental-omero-web-addons.yml
- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
Install latest iviewer on test60 so we can assess how far we are from making it the default IDR viewer. See:
- https://trello.com/c/LdGRTtZI/7-omeroiviewer-potential-blockers
Nginx caching is ***not*** activated at the moment.
> Install iviewer 0.6.0 as a secondary image viewer

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy-about.yml
- use final `0.6.0` version of IDR-OMERO (including https://github.com/IDR/bioformats/pull/10)
- update `/about` pages to use the latest website including studies/releases stats and about page updates
> prod60: final deployment tweaks

- ansible/group_vars/omero-hosts.yml
This should allow up to 1000 ROIs to be shown in iviewer, but will also allow larger API queries. Needs testing.
See https://trello.com/c/LdGRTtZI/1-omeroiviewer-as-the-default-viewer#comment-5bf52300aafbb91554148bfe
> Set omero.web.api.max_limit 1000

- ansible/idr-ftp.yml
Creates a locked local account on the IDR FTP server.
This account can be manually unlocked and a password set when required.
> idrftp alternate user account

- ansible/decommission/playbook.yml
See https://github.com/IDR/deployment/pull/144#pullrequestreview-173398053
While decommissioning `prod52`, I realized that the steps had to be run in a specific order. This playbook captures this order to simplify.
Note the steps aggregating/copying the various dumps/archives to `/uod/idr/versions` is not implemented but could probably be conceived as a folllow-up playbook.
> Add overarching decommissioning playbook

- ansible/templates/k8sproxy-haproxy.cfg.j2
Prevent external K8s API access.
This increases security by requiring K8s API access to be either tunnelled via the proxy (ssh proxy, connect to localhost), or from within the cluster (the GitLab runner is hosted inside the cluster and therefore has internal API access).
Relevant playbook: `ansible/k8s-k8sproxy.yml`
> k8s API access must be tunnelled via k8sproxy

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy-about.yml
The version: field in the footer is intended to show the deployment (prodXX, testXX, etc).
This partially reverts #148 which made it static
See
- https://github.com/IDR/idr.openmicroscopy.org/pull/33
- https://github.com/IDR/idr.openmicroscopy.org/pull/42
> Restore idr deployment version

- ansible/decommission/playbook.yml
To test: run against current prod 😀.
This playbook requires the `dnspython` module to be installed locally (on the host running Ansible).
> Check that decommission/playbook.yml is not run on current prod

- ansible/openstack-create-publicidr.yml
`prod63-omeroreadwrite` was manually resized: https://trello.com/c/sAMTUk7D/3-resize-omeroreadwrite-volume
> Increase omeroreadwrite vol to 1000 GB

- ansible/openstack-create-publicidr.yml
Candidate for `prod62`. As demonstrated by https://github.com/IDR/idr.openmicroscopy.org/pull/40, we are getting closer to the volume limit on the production IDR database instance. This raises the size to 300GB instead.
> Bump DB volume size to 300

- ansible/group_vars/omero-hosts.yml
The [version 2.5.0](https://pypi.org/project/django-cors-headers/2.5.0/) of django-cors-headers released 7 days ago drops support for Django 1.10 and earlier which breaks the current Web stack.
Noticed while deploying `prod65`. This [Travis build](https://travis-ci.org/sbesson/deployment/jobs/499443321) should illustrate the problem with the stack trace while deploying IDR.
Travis green should confirm this works with the current version of Django asked by OMERO.web.
> Cap version of django-cors-header deployed in IDR

- ansible/group_vars/omero-hosts.yml
This patch release included the backported Java SSL fix (https://github.com/openmicroscopy/openmicroscopy/pull/5951) as well as the OMERO.web enhancement to selectively disable feedback (https://github.com/openmicroscopy/openmicroscopy/pull/5982)
> Upgrade IDR OMERO version to 0.6.1

- ansible/group_vars/proxy-hosts.yml
- new studies statistics including prod65 publications
- first version. of Aspera download page
> Bump static website version to 2019.03.29

- ansible/group_vars/proxy-hosts.yml
- ansible/requirements.yml
This only decreases the Nginx expiry cache time, the inactive time is unchanged. This means if a cache update fails Nginx should return the stale version instead of failing (and should continue to refresh in the background)
Requires:
Closes https://github.com/IDR/deployment/issues/141
> Change cache_validity to 1d, background update, update nginx-proxy

- ansible/idr-omero.yml
Adjusts `idr-omero` playbook comment now we have just one read-write server.
> Update to describe current deployment.

- scripts/os-idr-snapshot.sh
As discussed in slack this removes the instance snapshots, only volumes are snapshot.
To be tested on the next release
> os-idr-snapshot.sh volumes only

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/molecule/publicidr/tests/test_proxy.py
- ansible/requirements.yml
https://trello.com/c/GpXEHzjV/519-cors-access-control-allow-origin-cached
https://github.com/IDR/deployment/pull/133/ added the CORS plugin to OMERO.web.
This doesn't work as expected because the idr-proxy Nginx caches the `Origin` header, which may contain the domain of the requesting client. This means it won't work for anyone visiting another domain from the cache version.
Instead this reverts the PR and unconditionally sets the CORS `Origin` header in the Nginx proxy config. This should be OK because idr.openmicroscopy.org is strictly a read-only public site, modifications are done by tunnelling and passing the proxy. If this changes in future this must be reviewed (though in that case the whole caching setup will need review which is an even bigger issue).
This also adds `/api` to …
> Move CORS header to Nginx, cache /api

- ansible/group_vars/omero-hosts.yml
I have no idea why this is needed. `/cell` and `/tissue` worked whereas `/gallery-api` didn't. I have no idea why `/gallery` does not seem to be required.
> OMERO.web public: change `/gallery` to `/gallery-api`

- ansible/group_vars/proxy-hosts.yml
This might improve performance slightly
Not deployed, since it makes testing changes on test64 harder
> Cache /gallery-api/

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- `omero-mapr 0.3.0` has been released without change since the last pre-release
- `omero-gallery 2.3.0a7` includes https://github.com/ome/omero-gallery/pull/41
- `idr.openmicroscopy.org` includes the new studies published in `prod67`
> Use final version of apps and website for IDR 0.6.7 release

- ansible/production-tests/test_web.py
Noticed during the release of `prod67`, the assumption of these tests (`/` redirecting to `/about/`) are no longer true and are updated.
> Update pytests following new gallery UI release

- ansible/group_vars/omero-hosts.yml
New PR at: https://github.com/ome/omero-gallery/pull/42
removes more IDR-specific code from the gallery app to settings, so we
need to configure additional settings to preserve the IDR usage of gallery.
> further gallery settings

- ansible/molecule/publicidr/molecule.yml
- ansible/requirements.yml
Pin Postgresql to 9.6.13 in molecule test to workaround https://forum.image.sc/t/fyi-not-possible-to-create-new-omero-instance-with-latest-postgresql-versions/26929
> Postgres version

- ansible/experimental-omero-web-addons.yml
- ansible/idr-bastion.yml
- ansible/idr-docker.yml
- ansible/idr-downloads.yml
- ansible/idr-dundee-nfs.yml
- ansible/idr-ftp.yml
- ansible/idr-haproxy.yml
- ansible/idr-local-users.yml
- ansible/idr-networks.yml
- ansible/idr-omero-readonly.yml
- ansible/idr-omero-web.yml
- ansible/idr-omero.yml
- ansible/idr-proxy-about.yml
- ansible/idr-proxy.yml
- ansible/idr-reboot-if-kernel.yml
- ansible/idr-reset-users-groups.yml
- ansible/idr-upgrade-dist.yml
- ansible/k8s-k8sproxy.yml
- ansible/management-fluentd.yml
- ansible/management-prometheus.yml
- ansible/management.yml
- ansible/openstack-create-ftp.yml
- ansible/openstack-create-publicidr.yml
- ansible/os-idr-volumes.yml
- ansible/requirements.yml
- ansible/roles/kubernetes/meta/main.yml
- ansible/roles/kubernetes/tests/requirements.yml
All Galaxy roles have been migrated to the Galaxy OME organization. This updates the IDR requirements file to use these new roles. Changes should be limited to renaming and have no functional impact.
Most roles are bumped to a patch release, usually the one associated with the role migration, which should be harmless. Below is the list of minor/major versions bumps:
- ome.basedeps: 1.0.0 -> 1.1.0 (Ubuntu 18.04 support)
- ome.cadvisor 0.2.0 -> 0.3.1 (Use official binary)
- ome.cli_utils: 1.0.0 -> 1.1.0 (add zsh)
- ome.docker: 2.3.0 -> 3.0.2 (removed support for distribution Docker)
- ome.ice: 2.1.1 -> 3.0.0 (drop support for Ice 3.5)
- ome.nfs_mount: 1.1.0 -> 1.2.1 (manage multiple versions of NFS)
- ome.nginx: 1.0.0 -> 1.1.1 (allow to set nginx_version)
- ome.omero_python_deps: 1.1.0 -> …
> Update Galaxy requirements

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
Connect to wss://idr-proxy/omero-ws
e.g. `omero login -u USER -w PASSWORD -s wss://test70/omero-ws`
This will allow applications on hosts which only allow http/https egress to use the IDR OMERO API, for example mybinder.org
> Enable external omero websockets

- inventories/openstack-idr.py
Python 3 fixes for inventories/openstack-idr.py
WARNING: the openstack library does some hidden caching, it's not enough to delete the cache files. If you immediately switch from Python 2 to Python 3 the inventory won't work properly- the SSH proxy autodetection fails. Delete any cache files you can find and wait a bit.
> inventories: py3 compatibility

- ansible/requirements.yml
Follow-up of #201 
With this role version, it should be possible to deploy IDR using a Python 3 environment. Tested while redeploying `test70`
> Bump ome.munin_node requirements to 1.2.1-openmicroscopy2

- ansible/group_vars/omero-hosts.yml
1 more config from https://github.com/ome/omero-gallery/pull/42
This regex uses the Study ```Name``` (e.g. ```idr0010-doil-dnadamage/screenA```) and produces e.g. ```idr0010A```.
See query at https://github.com/ome/omero-gallery/pull/42/files#r299405852
As the code might change there, best to wait for that PR to be merged before this one.
> Add config for Gallery study_short_name.

- ansible/group_vars/proxy-hosts.yml
Should be the final deployment PR for `prod70`
> Bump static website version to 2019.09.17

- .travis.yml
See https://github.com/philpep/testinfra/blob/2.1.0/CHANGELOG.rst
This release includes a fix for the socket tests with new verions of ss. This
version seems to have made it into the base iproute CentOS packages
See https://github.com/IDR/deployment/pull/204#issuecomment-532266520 for the initial bug report. This should fix the IPv6 socket listening tests and let Travis CI pass
Proposing to get this in as a quick fix. Potential next steps up for discussion:
- force the minimal `testinfra` version in the `ome-ansible-molecule` package
- bump to `molecule 2.22` which depends on a recent version of `testinfra` (might require other fixes)
- do not override `testinfra` but investigate  downgrading the version of `ss` installed by `iproute` in the `prepare.yml` playbook
> Install testinfra 2.1.0

- ansible/openstack-create-ftp.yml
- ansible/openstack-create-k8s.yml
- ansible/openstack-create-publicidr.yml
- docs/provisioning.md
Given the number of issues associated with this step, the floating IP association is migrated as a manual step post-provisioning.
> Do not assign floating IP on VM creation

- ansible/group_vars/omero-hosts.yml
- ansible/requirements.yml
Switch to using a virtualenv for OMERO.server.
This also means the metadata and render plugins can be installed automatically.
Also a minor bump to omero-web
> OMERO.server virtualenv

- ansible/group_vars/omero-hosts.yml
Includes the two following bug fixes
- https://github.com/ome/omero-mapr/pull/50
- https://github.com/ome/omero-mapr/pull/44
Deployed on `test71`. In addition to executing the playbook, I had to wipe the `omerostatic` cache and reload `nginx`. I wonder whether we want to do that more systematically in the deployment playbooks
```
[sbesson@test71-proxy ~]$ sudo rm -rf /var/cache/nginx/omerostatic/
[sbesson@test71-proxy ~]$ sudo service nginx reload
Redirecting to /bin/systemctl reload nginx.service
```
> Bump omero-mapr version to 0.3.2

- ansible/group_vars/proxy-hosts.yml
This study is scheduled for publication in an upcoming IDR release. As the publication went online, the raw data is available via Aspera. In the interim, this allows the link to redirect to the download page.
Deployed on `test71`. Proposing to deploy on `prod71` immediately and tag 
cf25e5a  as `IDR-0.7.1-1`. The commit will need reverting for `prod72` release.
> Add study-specific redirects to the download page

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy.yml
Noticed a mistake whilst looking into changing the load-balancing for web-sockets. Currently omero-ws is proxied to the omeroreadonly servers reserved for OMERO.web instead of the ones ddesigned for direct external connects.
Note yet deployed
This is some other undeployed change:
```
TASK [ome.nginx_proxy : nginx | proxy config] **********************************
--- before: /etc/nginx/conf.d/proxy-default.conf
+++ after: /Users/spli/.ansible/tmp/ansible-local-64735ngztx6__/tmpr26fg1l6/nginx-confd-proxy.j2
@@ -243,5 +243,6 @@
add_header Access-Control-Allow-Origin $allow_origin;
if ($request_uri ~ /search/\?query=Name:idr0065) { return 302 /about/download.html;}
+    if ($request_uri ~ /search/\?query=Name:idr0068) { return 302 /about/download.html;}
}
```
The relevant change:
```
TASK …
```
> omero-ws should use external not reserved omero hosts

- .travis.yml
- ansible/idr-01-install-idr.yml
- ansible/idr-ebi-nfs.yml
- ansible/idr-firewall.yml
- ansible/idr-networks.yml
- ansible/management-fluentd.yml
- ansible/management-grafana.yml
- ansible/management-prometheus.yml
- ansible/management.yml
- ansible/molecule/ftp/molecule.yml
- ansible/molecule/publicidr/molecule.yml
- ansible/requirements.yml
Changes for extcloud01:
- added customisations for things like network interfaces (default unchanged)
- added a firewall (disabled by default but we should consider enabling it on the next prod server too)
- NFS config uses the role and private variables (this is a change relative to `prod73` but should've been done ages ago)
- Fixed SELinux permissions on Nginx cache, requires https://github.com/ome/ansible-role-nginx-proxy/pull/27
> extcloud01: customisations and bug fixes

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- Ensures the canonical IDR URL is always used in API responses.
- Bumps iviewer with the projection limit.
- Update about pages (prod80a)
Deployed on `prod80`.
> Prod80 final updates

- ansible/group_vars/proxy-hosts.yml
Adds a holding page where idr-analysis can be redirected
Deployed to prod80a, DNS updated
> Add ebi-migration page

- ansible/idr-dundee-nfs.yml
This hasn't been used for ages, we should probably move it to the private config since it's useless for anyone else but that can happen later. For now this updates it to work with the current internal. UoD setup.
> Update UoD NFS config

- ansible/group_vars/proxy-hosts.yml
Currently we have 2 OMERO.server/OMERO.web for public web access, and 2 OMERO.server (with unused OMERO.web) for API access via 4064 and other load-balanced ports.
This temporarily changes the allocation to 3 servers for front-end web and one for 4064 API access to handle an expected increase in traffic.
Not yet deployed, needs discussion. Relevant changes from dry-run against prod80b:
```diff
TASK [ome.nginx_proxy : nginx | proxy upstream servers] ************************
--- before: /etc/nginx/conf.d/proxy-upstream.conf
+++ after: /Users/spli/.ansible/tmp/ansible-local-23171vbpqocoi/tmp74v4e_gz/ngin
x-confd-proxy-upstream.j2
@@ -4,10 +4,10 @@
ip_hash;
server 192.168.101.15;
server 192.168.101.16;
+  server 192.168.101.17;
}
upstream omeroreadonlywebsockets {
ip_hash;
-  server …
```
> Allocate extra server to web, remove from 4064

- ansible/group_vars/omero-hosts.yml
Deployed successfully on the server. 
This is in prep of using https://github.com/ome/omero-upload/blob/18277a7669d37296ecb49f6e8102ec89b99ca0a8/src/omero_upload/library.py#L76-L88 method for in-place import of attachments to IDR.
cc @sbesson
> Add omero-upload as addon install

- ansible/group_vars/omero-hosts.yml
This patch release includes the MetaXpress fix required for idr0081
To be tested in a testing resource first to confirm memo files are not invalidated. Current target release: `prod82`
> Consume 0.6.3 release of IDR Bio-Formats

- ansible/group_vars/proxy-hosts.yml
These URLs pointing to figure panels can be reused in tweets and press releases
Changes have been applied manually in production on `prod80a` and `prod80b` so the main test here is to run the `idr-proxy.yml` in check-mode against either or both servers and test there is no diff (or only whitespaces)
> Add study-level redirects for figures of idr0083

- ansible/decommission/archive-instance-services.yml
- ansible/group_vars/database-hosts.yml
- ansible/group_vars/omero-hosts.yml
- ansible/molecule/publicidr/tests/test_database.py
- ansible/requirements.yml
This requires a manual PG dump and restore on the IDR servers.
Requires:
> PostgreSQL 11

- ansible/group_vars/proxy-hosts.yml
This reverts commit d28d764426e4c1c915c995f27d3cfadffcf9b189.
Reverts #233
```diff
TASK [ome.haproxy : Copy HAProxy configuration in place.] **********************
--- before: /etc/haproxy/haproxy.cfg
+++ after: /Users/spli/.ansible/tmp/ansible-local-27293uyiv4yzj/tmpo4wkthkz/haproxy.cfg.j2
@@ -35,12 +35,20 @@
option tcplog
timeout client 10m
log 127.0.0.1 local3
+frontend omero4064-1
+    bind *:14061
+    mode tcp
+    default_backend omero4064-1
+    option tcplog
+    timeout client 10m
+    log 127.0.0.1 local3
backend omero4064
mode tcp
balance source
option tcplog
+    server omero4064-192_168_101_17 192.168.101.17:4064 check
server omero4064-192_168_101_18 192.168.101.18:4064 check
timeout connect 10s
timeout server 10m
@@ -49,6 +57,13 @@
mode tcp
balance source
option tcplog
+ …
```
> Revert "Allocate extra server to web, remove from 4064"

- ansible/group_vars/omero-hosts.yml
Adds https://pypi.org/project/omero-rois package, which is handy if one needs to convert segmented images into ROIs.
> Add omero_rois

- ansible/idr-firewall.yml
Minor fix to which hosts are targetted by the firewall. idr-ftp shouldn't be modified because it's runnign Docker which does it's own iptables management.
> firewall: be explicit about hosts, exclude ftp

- ansible/group_vars/omero-hosts.yml
Noticed while preparing the talk for the 2020 Community meeting.
Given the importance of this biomolecular annotation for compound screens as well as the work engaged to rationalize its ontology, this PR proposes to add the category to the top-level search box.
Target: `prod83`
> Add compound to the list of image attributes searchable by IDR gallery

- ansible/templates/omero-client.json.j2
Closes https://github.com/IDR/deployment/issues/245
Deployed to `test84`
```py
from idr import connection
conn = connection('test84.example.org', verbose=2)
for p in conn.listProjects():
print(p.name)
```
> Include public user/pass in omero-client.json

- ansible/group_vars/omero-hosts.yml
Includes https://github.com/IDR/bioformats/pull/21 (`idr0048`) and https://github.com/IDR/bioformats/pull/22 (`idr0078`)
> Bump IDR Bio-Formats version to 0.6.4

- ansible/decommission/archive-db.yml
- ansible/decommission/archive-logs.yml
See https://docs.ansible.com/ansible/latest/modules/fetch_module.html#notes.
Tested with the `archive-logs.yml` playbook which was seemingly hanging when fetching the `prometheus` archive.
> Do not become when fetching dumps and logs during decommissioning

- ansible/group_vars/proxy-hosts.yml
This PR uses the latest tag of the website (https://github.com/IDR/idr.openmicroscopy.org/releases/tag/2020.08.19)
A link in ITR was updated and https://github.com/IDR/idr.openmicroscopy.org/pull/91 merged after prod86 was made available
The link to the ilastik notebook is currently broken. (https://github.com/ome/omero-guide-ilastik/pull/21 for background)
This should be deployed to live prod before the next IDR release.  ITR is mentioned in the submitted CSHL abstract 
I cannot deploy it
> idr website update

- ansible/group_vars/omero-hosts.yml
During testing of https://github.com/IDR/idr-utils/pull/11 it turned out that no pandas are installed on idr-next.
This PR is adding the line to the playbook.
The command run manually as 
``/path-to/pip install pandas``
showed the version to be 1.1.0
@manics
> Add pandas to notebook

- ansible/group_vars/proxy-hosts.yml
Reverts IDR/deployment#218
`idr0048` has now been officially released - see https://idr.openmicroscopy.org/search/?query=Name:48
However a custom redirect had been added to redirect https://idr.openmicroscopy.org/search/?query=Name:idr0048 to the Aspera download page. This is no longer necessary and this link should display the gallery result instead
> Revert "Add redirect for idr0048 to downloads"

- ansible/group_vars/omero-hosts.yml
This is primarily driven by the  timestamp bug fix in iviewer. As per the dependency, it also pulls omero-web 5.7.0
See 
- https://github.com/ome/omero-iviewer/blob/v0.10.1/CHANGELOG.md
- https://github.com/ome/omero-web/blob/v5.7.0/CHANGELOG.md
> Bump omero-iviewer to version 0.10.1

- ansible/group_vars/proxy-hosts.yml
This includes the stats for `prod86` and `prod87` and has been deployed in production - see idr.openmicroscopy.org/about/studies.html
> Deploy 2020-09-03 version of the website including updated stats

- ansible/group_vars/proxy-hosts.yml
These studies are scheduled for publication in upcoming releases of IDR. In the meantime, the searches should redirect to the download page as the raw data is publicly available.
To be deployed on `idr-next` for testing, then on `idr`
> Add redirects for idr0078, idr0089, idr0090 and idr0094

- ansible/decommission/archive-db.yml
- ansible/decommission/archive-instance-services.yml
- ansible/decommission/archive-logs.yml
Small improvements:
- following a RFE from @joshmoore, ebabdd3  should ensure monitoring and slack alerting agents are shut down before stopping the other services
- 28f6ec6 primarily aims at speeding up the decommissioning process. At the moment, the DB dump/log archives are first downloaded locally then copied over to our UoD location. Skipping the local copy step, I ended up simply rsyncing the logs/dumps into their final location on `idr0-slot3` as:
```
rsync -av idr-next:/tmp/prod86-proxy-* . --progress
rsync -av -e "ssh idr-next ssh" database:/tmp/prod86-database-* . -vv --progress
rsync -av -e "ssh idr-next ssh" management:/tmp/prod86-management-* . --progress
```
If the above sounds like the canonical to go, happy to more simply remove the `fetch` commands.
With the transfer step …
> Decommissioning improvements

- ansible/idr-s3gateway.yml
Changes the `idr-ftp` `idr-upload` read-write authenticated proxy to only apply to virtualhost `idr-ftp.openmicroscopy.org`.
All other hostnames will be redirected to https://idr.openmicroscopy.org/
> Add idr-s3.openmicroscopy.org readonly public proxy for /idr

- ansible/idr-ftp-monitoring.yml
- ansible/requirements.yml
- ansible/templates/idrftp-alert-rules-yml.j2
This installs a full updated prometheus deployment on idr-ftp to give us immediate disk space alerts. Later it will be replaced by a dedicated shared monitoring/management server: https://github.com/IDR/deployment/issues/264
`ssh <testftp-server> -L 19090:localhost:9090`
- Prometheus alerts dashboard: http://localhost:19090/alerts
- `/data` % free http://localhost:19090/graph?g0.range_input=1h&g0.expr=(node_filesystem_avail_bytes%7Bmountpoint%3D%22%2Fdata%22%7D%20*%20100)%20%2F%20node_filesystem_size_bytes%7Bmountpoint%3D%22%2Fdata%22%7D&g0.tab=0
An alert should be sent to Slack `#idr-notify-testftp` (needs to be renamed `#idr-notify-idrftp` for production) if the free disk space on `/data` falls below 10%. The current volume on the test server is 100 GB and I've created an 85GB file in …
> Temporary monitoring for idr-ftp

- ansible/requirements.yml
Update prometheus postgres exporter to work with PostgreSQL 11.
Closes https://github.com/IDR/deployment/issues/244
> ome.prometheus_postgres 0.4.0

- ansible/group_vars/omero-hosts.yml
Not deployed anywhere, we can wait for the next test server
> OMERO.web 5.8.0 OMERO.py 5.8.0

- ansible/openstack-create-pilotidr-omero.yml
- ansible/openstack-create-publicidr.yml
The recent import work is bringing us closer to the 1000G size of the `/data` volume. On `prod88`
```
[sbesson@prod88-omeroreadwrite ~]$ df -h
Filesystem                    Size  Used Avail Use% Mounted on
devtmpfs                       32G     0   32G   0% /dev
tmpfs                          32G     0   32G   0% /dev/shm
tmpfs                          32G  720K   32G   1% /run
tmpfs                          32G     0   32G   0% /sys/fs/cgroup
/dev/vda1                     100G  9.4G   91G  10% /
/dev/vdb                     1000G  884G  117G  89% /data
10.35.106.250:/fg_bioimage    600T  321T  280T  54% /nfs/bioimage
10.35.106.251:/fg_biostudies  302T  249T   53T  83% /nfs/biostudies
tmpfs                         6.3G     0  6.3G   0% /run/user/11615
tmpfs                         6.3G …
```
> Expand OpenStack data volume to 1.2 TB

- ansible/group_vars/omeroreadwrite-hosts.yml
- ansible/group_vars/proxy-hosts.yml
This is needed to re-cache mapr Homo sapiens queries
> Set omeroreadwrite web timeout to 900

- ansible/group_vars/omero-hosts.yml
See https://github.com/ome/omero-py/blob/v5.8.2/CHANGELOG.md and
https://github.com/ome/omero-web/blob/v5.8.1/CHANGELOG.md for the list of changes
Fixes https://github.com/IDR/idr-utils/issues/27
With this change `omero` commands piped to an output file requiring an interactive user input should fail rather than hang.
> Bump omero-py to 5.8.2 and omero-web to 5.8.1

- ansible/group_vars/proxy-hosts.yml
> Deploy 2020.10.05 version of idr.openmicroscopy.org/about

- ansible/idr-s3gateway.yml
Having the header added twice broke clients. Removing
for the moment, but a conditional addition would be
safest.
see: https://forum.image.sc/t/mirroring-idr-zarr-datasets/41136/16?u=joshmoore
> Drop addition of Access-Control header

- ansible/idr-ftp-monitoring.yml
This is useful for monitoring performance
We could install this on all VMs, for now it's just idr-ftp since we're investigating S3 performance issues.
> Install dstat on idr-ftp

- ansible/templates/omero-client.json.j2
Once this is deployed
```py
from idr import connection()
c = connection('idr.openmicroscopy.org')
```
should automatically use websockets.
Requires https://github.com/IDR/deployment/pull/287
> omero-client.json: use wss (websockets)

- ansible/grafana-dashboards/idr-per-server.json
- ansible/grafana-dashboards/idr-sessions.json
- ansible/grafana-dashboards/idr-vertical.json
- ansible/idr-ftp-monitoring.yml
- ansible/management-grafana.yml
- ansible/requirements.yml
Upgrades prometheus and grafana.
Partly related to https://github.com/IDR/deployment/issues/264
The main breaking changes are changes to metric names, which is why some of the Grafana dashboards are modified.
> Main IDR monitoring upgrade

- ansible/grafana-dashboards/idr-postgresql.json
- ansible/management-fluentd.yml
- ansible/management-prometheus.yml
- ansible/openstack-create-pilotidr-servers.yml
- ansible/openstack-create-pilotidr.yml
- ansible/requirements.yml
- inventories/openstack-idr.py
- One monitoring server for all pilot deployments
- Need to add additional openstack group metadata to each pilot IDR, can be done by running the `provision` step on each idrNNNN pilot (metadata will be updated with no downtime)
- Requires https://github.com/IDR/ansible-role-openstack-idr-instance/pull/5 due to the extra metadata going over the limit for a single property
> Add monitoring to the pilot deployments

- ansible/grafana-dashboards/idr-postgresql.json
- ansible/group_vars/omero-hosts.yml
- ansible/openstack-create-publicidr.yml
Disable all components except Blitz and Tables
Fixes the postgres grafana dashboard (was exported with the wrong options in https://github.com/IDR/deployment/pull/299)
> OMERO.py 5.9.0rc1: disable unused OMERO components

- ansible/group_vars/proxy-hosts.yml
This has been deployed manually on `prod91`
> Use 2020.12.17 version of the website

- .github/workflows/molecule.yml
- ansible/idr-haproxy.yml
- ansible/idr-omero-readonly.yml
- ansible/idr-omero.yml
- ansible/idr-proxy-about.yml
- ansible/idr-proxy.yml
- ansible/molecule/ftp/tests/test_default.py
--depends-on https://github.com/ome/action-ome-ansible-molecule/pull/1
Not in scope for `prod92` but to be tested when spinning up `prod93`
> Update playbooks with Ansible 2.8/Molecule 2.22

- ansible/openstack-create-infrastructure.yml
- ansible/vars/openstack-vars.yml
- docs/operating-procedures.md
- docs/provisioning.md
Following #311 this removes mentions of the VAE deployment in a few remaining places (code + documentation) /cc @jburel
> Remove remaining documentation references to the VAE deployment

- ansible/idr-downloads.yml
- ansible/openstack-create-pilotidr-servers.yml
- ansible/requirements.yml
This PR performs a routine update of the Ansible roles to consume the latest releases. Most of the the increments are patch releases following the Ansible 2.8 upgrade. Below are listed the minor/major bumps with a list of the features 
- ome.docker 3.0.2 -> 3.1.1: allow to override yum repo
- ome.ice 4.0.1 -> 4.2.0: do not use runtime package, use set become
- ome.nfs_mount 1.2.1 -> 1.3.0: support mount state and multiple nfs versions
- ome.nginx 2.0.1 -> 2.1.1: allow to manage nginx without systemd
- ome.nginx_proxy 1.13.0 -> 1.15.1: additional directives, allow to not restart nginx via systemd
- ome.omero_logmonitor 2.1.1 -> 3.0.1: upgrade to Python 3
- ome.omero_server 3.2.0 -> 3.3.1: use ome.python3_virtualenv
- ome.omero_web 3.0.1 -> 3.1.1: use ome.python3_virtualenv
- ome.prometheus …
> Bump Ansible roles to their latest released version

- scripts/os-idr-delete.py
- scripts/os-idr-swapip.py
Fixes an issue encountered during the deletion of `prod93b` resources related to the detected ports. To reproduce the problem, run a dry-run deletion against an existing environment (or a freshly created one):
```
./scripts/os-idr-delete.py prod95 --type all
```
After confirm the environment to be deleted (`prod95`), the output of the command should list 4 ports to be deleted in the `Networks` section instead of one. 
Debugging reveals that the issue comes from https://github.com/IDR/deployment/blob/e8db873933dbb6e38439b19ba52731460eaeb188/scripts/os-idr-delete.py#L94-L96 which returns all ports and is ignoring the  `device_owner` and `network_id` filters.
While trying to track the issue, I noticed that the final release of `shade`, 1.33.0, happened a year ago with the package is …
> Use openstacksdk rather than shade for resources deletion

- ansible/decommission/archive-db.yml
The DB bump has been quite reliably the bottleneck of the decommissioning process. This tries to enable parallel dump using the directory format
> Improve DB archiving playbook by using parallel dump

- ansible/group_vars/omero-hosts.yml
In the context of the upcoming `idr0072`, this defines a new Protein Supplementary map annotation.
> Add mapr configuration for Protein Supplementary annotations

- ansible/group_vars/omero-hosts.yml
See https://www.openmicroscopy.org/2021/03/17/omero-web-5.9.0.html
Also bumps OMERO.iviewer to the latest patch release
> Bump OMERO.web version to 5.9.1

- ansible/requirements.yml
The main goal of these patch release increments should decrease the deprecation warnings when performing a new deployment
> Bump ome.sudoers and ome.cli_utils roles

- ansible/management-fluentd.yml
The goal of this change is to restrict the notify channel to Prometheus (and
possible Munin) alerts and redirect the logs from the various data sources
collected by fluentd (nginx, omero.master) to the logs channel.
> Redirect fluentd logs to idr-logs channel

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/omeroreadwrite-hosts.yml
- ansible/idr-omero-readonly.yml
- ansible/idr-omero.yml
- ansible/requirements.yml
Follow-up of #329, this PR:
- installs self-signed SSL certificates on the read-write server using `omero_server_selfsigned_certificates`
- add variable to override the `lib/client` JARs and use the latest `omero-blitz/omero-romio` JARs
- updates the IDR Bio-Formats variables to use the same dictionary structure
> Support OpenJDK 11.0.11

- ansible/management-prometheus.yml
If OMERO services are down, this should generate alerts every 30 min
See discussion at https://github.com/IDR/deployment/pull/333. Proposing to deploy this on `prod98`
> Reduce interval between successive groups of alters to 25m

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
Deploy omero-figure on an IDR environement.
Due to the read-only nature, figures cannot be saved back onto the server.
> Install omero-figure

- ansible/requirements.yml
Test the changes introduced in https://github.com/ome/ansible-role-nginx/pull/11.
For comparison https://github.com/IDR/deployment/runs/2858097914 (current HEAD of `origin/master`) is failing with
```
RUNNING HANDLER [ome.nginx_proxy : restart nginx] ******************************
fatal: [idr-ftp]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
```
and
```
RUNNING HANDLER [ome.nginx_proxy : restart nginx] ******************************
fatal: [idr-proxy-docker]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error …
```
> Consume ome.nginx role change disabling epel repository

- ansible/group_vars/omero-hosts.yml
The 2 plugins have been tested and released during the preparation of prod99
Both have been installed in prod99
cc @sbesson @dominikl @francesw
> bump metadata to 0.8.2 and iviewer to 0.11.1

- ansible/requirements.yml
The new security group is necessary to access NFS data on the Embassy Cloud v4 infrastructure
> Embassy Cloud v4: use new Openstack roles with the NFS security group

- ansible/openstack-create-pilotidr-servers.yml
This should allow the dev server need to have access to the storage for conversion purposes
> Override idr_vm_security_groups in pilot dev server provisioning plabook

- ansible/idr-ftp.yml
- ansible/molecule/ftp/tests/test_default.py
- ansible/molecule/ftp/tests/upload_test.sh
- ansible/openstack-create-ftp.yml
- docs/idr-ftp-s3.md
- define a single FTP security group
- add the 21 port to the FTP security group
> Use standard 21 port for new FTP deployment

- ansible/idr-01-install-idr.yml
- ansible/idr-02-services.yml
- ansible/idr-export.yml
- ansible/molecule/ftp/molecule.yml
- ansible/openstack-create-pilotidr-servers.yml
- create new `idr-export` service playbook to populate `{{ idr_environment_idr }}-dev` server with conversion prerequisites
> Zarr server: add service playbook

- ansible/openstack-create-pilotidr-servers.yml
- ansible/requirements.yml
Consumes the parameter introduced in https://github.com/ome/ansible-role-openstack-volume-storage/pull/3
> Update the pilot dev server provisioning playbook to specify the volume type

- ansible/group_vars/omero-hosts.yml
See https://www.openmicroscopy.org/2021/10/14/omero-web-5.11.0.html
Also comment out the OMERO.py pinning, assuming the rolling deployment should
periodically bring the latest OMERO.py release
> Deploy OMERO.web and OMERO.figure security release to IDR

- docs/object-store.md
- scripts/s3-create-bucket.sh
- explain bucket creation, policy and CORS configuration setting
> Add first version of instructions for the IDR object store

- ansible/requirements.yml
- scripts/os-idr-delete.py
--depends-on https://github.com/ome/ansible-role-openstack-volume-storage/pull/4
Following recent upstream changes in Embassy Openstack, the cloning of volumes is done via the creation of intermediate snapshots. The lifecycle of these snapshots is tightly coupled to the child volumes and the deletion script is adjusted to delete the volumes before the snapshots.
> Openstack: handle new volume creation logic

- ansible/idr-ftp.yml
This should bring an up-to-date system and vsftpd version (see https://github.com/ome/vsftpd-anonymous-upload-docker/pull/7) to prevent segfaults happening on the FTP server
```
[sbesson@idrftp-ftp ~]$ sudo grep segfault /var/log/messages
Jan 18 04:14:57 idrftp-ftp kernel: vsftpd[26832]: segfault at 0 ip 0000559d4028ea7a sp 00007fffd8cbba98 error 4 in vsftpd[559d40280000+1f000]
Jan 18 17:52:06 idrftp-ftp kernel: vsftpd[11759]: segfault at 0 ip 000055d2f2797a7a sp 00007fffa19f56f8 error 4 in vsftpd[55d2f2789000+1f000]
Jan 19 07:35:30 idrftp-ftp kernel: vsftpd[18813]: segfault at 0 ip 0000557d81a5ba7a sp 00007ffe163aa018 error 4 in vsftpd[557d81a4d000+1f000]
[
```
/cc @dominikl
> Deploy 0.2.2 tag of vsftp Docker image

- ansible/idr-ftp.yml
- ansible/idr-omero-readonly.yml
- ansible/management-fluentd.yml
- ansible/requirements.yml
This PR contains as set of adjustements to the IDR playbooks to run a full deployment using Ansible 2.9. All changes are related to the usage of Ansible tests (`search`, `changed`) as filters which is dropped.
Two underlying role changes are required: https://github.com/ome/ansible-role-omero-user/pull/7 and https://github.com/ome/ansible-role-network-cloud-interfaces/pull/6
> Ansible 2.9 support

- ansible/group_vars/omero-hosts.yml
See https://www.openmicroscopy.org/2022/02/18/omeroweb-django-upgrade.html
> Bump OMERO.web and apps to versions compatible with Django 3.2

- ansible/group_vars/omero-hosts.yml
With https://github.com/IDR/idr-gallery/pull/2, the 'root' (app to appear at the home page) is now `idr_gallery`.
Also, this adds "Light sheet fluorescence microscopy" as a category (now found under "Group Studies by type").
This is currently deployed for testing and seems to be working fine:
- The / home URL is pointing to `idr_gallery` and the app is installed OK.
- /cell/search/ and related URLs added to public url filter are working
- the "Lightsheet microscopy" category and "Others" category are showing correctly under "Group Studies by Type"
NB: now that the PR above includes all the current config as default IDR behaviour, we don't need it in `omero-hosts.yml` unless we need to update it.
> Idr gallery config

- ansible/group_vars/proxy-hosts.yml
- ansible/idr-02-services.yml
- ansible/idr-proxy.yml
- ansible/idr-searchengine.yml
- ansible/openstack-create-publicidr.yml
Fixes #370
As discussed on the issue, this PR implements option 3 and creates a new VM of similar compute capacity to `omeroreadwrite` and some dedicated storage.
To be deployed on `test107`
> Update playbooks to deploy searchengine in production deployment

- ansible/group_vars/searchengine-hosts.yml
- ansible/idr-searchengine.yml
Although this configuration item has a default value in the app configuration file, we may need to refer to another file  for verification rather than the default one `https://raw.githubusercontent.com/IDR/idr.openmicroscopy.org/master/_data/studies.tsv `
> add task to configure  IDR_TEST_FILE_URL

- ansible/openstack-create-pilotidr-servers.yml
- ansible/openstack-create-publicidr.yml
- ansible/openstack-create-volumes.yml
Routine expansion of the OMERO data volume as the imported data grows to bring the data usage below the 80% threshold
> Bump omeroreadwrite data volume to 1.5TB

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/omeroreadonly-hosts.yml
- ansible/group_vars/omeroreadwrite-hosts.yml
- ansible/idr-omero-readonly.yml
The self-signed SSL certificates were initially deployed on the read-write hosts to fix import issues but they might be required on all read-only servers to fix access via the Java API
> Configure self-signed certificates on all OMERO hosts

- ansible/decommission/playbook.yml
- ansible/idr-00-preinstall.yml
- ansible/idr-01-install-idr.yml
- ansible/idr-02-services.yml
- ansible/idr-03-postinstall.yml
- ansible/idr-09-monitoring.yml
- ansible/openstack-create-infrastructure.yml
Updates the IDR playbooks as these directives will be dropped in Ansible 2.12
> Replace deprecated include directive by import_playbook

- ansible/files/deploy
- ansible/group_vars/proxy-hosts.yml
- ansible/idr-proxy-about.yml
Similarly to a change that was made for www.openmicroscopy.org, this removes the requirement to track the explicit version of the static website deployed at https://idr.openmicroscopy.org/about/. The ome.deploy_archive job is replaced by a simple Python script which polls hourly for new GitHub releases and deploys them if it finds them.
The environment version is stored as a source of truth under /srv/www/VERSION and copied as part of the deployment script.
This was a long standing improvement in my backlog especially in terms of released but it was primarily motivated by https://github.com/IDR/deployment/commit/36fc6ce570b6e2b7d8b71f19acf1136565159640 as the current workflow for updating the IDR static website requires 1- a tag + release on the source repo 2- the execution of an Ansible …
> Refactor updates to the IDR static website

- ansible/idr-ftp.yml
- ansible/openstack-create-pilotidr-servers.yml
This should allow new key pairs to be uploaded/used while creating new pilots
> Add openstack_idr_keypairs role to pilot provisioning playbook

- ansible/decommission/archive-instance-services.yml
- ansible/group_vars/database-hosts.yml
- ansible/group_vars/omero-hosts.yml
- ansible/molecule/publicidr/tests/test_database.py
- ansible/requirements.yml
As the current PSQL used in IDR is running into its EOL in 5 months time (https://endoflife.date/postgresql), this investigate the deployment steps to upgrade to a more recent version.
PSQL 13 was chosen mostly within the wider context of upgrading the Linux distribution of IDR in the upcoming months. This version matches the default version shipped with Rocky Linux 9. If we decide to go with a different distribution, it should be easier
In addition to making the playbook changes, a new PSQL upgrade procedure was tested. Previous upgrades (#238 #227)  have involved the classic `pg_dump/pg_restore` workflow which requires provisioning and/or copying a large dump archive given the size of the IDR database (~600G). Recent versions of PSQL include a …
> Upgrade PSQL version to 13

- ansible/idr-ftp-monitoring.yml
- ansible/management-fluentd.yml
- ansible/management-prometheus.yml
- ansible/management.yml
The current workflow involves the creation (or renaming) of a pair of dedicated Slack channels for each new IDR environment. This adds the logic allowing to control the Slack channels via private variables and use a reduced set.
> Allow to override the Slack channel used for logs/notifications

- ansible/group_vars/searchengine-hosts.yml
- ansible/idr-elasticsearch.yml
- ansible/idr-searchengine.yml
This PR updates Elasticsearch to version 8 (8.8.1). It also secures the connection between the searchengine and the elasticsearch cluster and between the elasticsearch cluster nodes themselves.
I have tested it locally and it worked fine. I am now testing it in `pilot-idr0000-omeroreadwrite`.  
This  PR required changes to the search engine code and I will create a PR for it soon.
> Update to Elasticsearch 8 and secure the connection between searchengine and elasticsearch

- ansible/idr-ebi-nfs.yml
- Install [goofys](https://github.com/kahing/goofys) under /usr/local/bin
- Install fuse
- Use Ansible mount command to mount the bucket using `/etc/fstab`
- Take an input dictionary defining the bucket, mount points and options
> Update EBI NFS share playbook to also mount S3 buckets

- ansible/requirements.yml
OMERO.server deployed using the latest release of omero-certificates no longer supports the deprecated TLS 1.0 and 1.1 protocols. The monitoring agent needs to create an OMERO.py client able to negotiate a connection with TLS 1.2. The latest version of the role uncaps the version of OMERO.py installed in the virtual environment which was previously set to 5.6.0.
> Consume version 0.3.6 of the OMERO Prometheus role

- ansible/files/deploy
- ansible/idr-00-preinstall.yml
- ansible/idr-journald.yml
- ansible/molecule/ftp/molecule.yml
- ansible/vars/openstack-vars.yml
- docs/deployment.md
- docs/idr-ansible.sh
- docs/operating-procedures.md
- docs/provisioning.md
Follow-up of #413 this reviews the last few places including references to CentOS 7 in these playbooks and instructions
> Centos cleanup

- ansible/group_vars/omero-hosts.yml
bump iviewer 0.14.0
cc @jburel
> bump iviewer 0.14.0

- ansible/group_vars/omero-hosts.yml
- ansible/idr-omero-readonly.yml
- ansible/idr-omero.yml
- ansible/requirements.yml
NB: this is on top of @dominikl's PR: https://github.com/IDR/deployment/pull/420/ following the discussion there, particularly https://github.com/IDR/deployment/pull/420#issuecomment-2178112947
@sbesson: I have added the list of jars under `omero_client_jars` but as I understand it, this will attempt to load those jars from the OME artifactory, not from maven central?
I added a variable `maven_central_baseurl: "https://repo1.maven.org/maven2"` and I should probably list the jars under a different variable like `omero_client_maven_jars` but I don't know where to update the logic that would consume that list.
cc @dominikl @jburel
> Bump zarr reader 0.5.1

- ansible/group_vars/omero-hosts.yml
> Bump ZarrReader to 0.5.2 and omero-server to 5.6.12

- ansible/group_vars/omero-hosts.yml
See title. For testing this probably has to be applied to pilot-idr0159, because the field "Antibody Name" doesn't exist in other deployments (renamed from "Antibody").
/cc @sbesson
> Add antibody name to mapr search

- ansible/requirements.yml
This PR fixes the iptables deployment issue by using the iptables_raw role from this https://github.com/ome/ansible-role-iptables-raw/pull/13.
It is extracted from https://github.com/IDR/deployment/pull/438.
> update iptables role

- ansible/requirements.yml
As discussed, bumping the role after release.
cc @sbesson @dominikl
> Bump ome.nginx_proxy to 1.16.2 - ssl changes

- ansible/group_vars/omero-hosts.yml
- ansible/group_vars/proxy-hosts.yml
- ansible/requirements.yml
This represents the changes I have been making manually on idr-testing with the replacement of mapr searches with searchengine, described at https://github.com/IDR/idr-gallery/pull/45
Summary of changes:
- Move mapr app *AFTER* idr-gallery so that URLs such as `/mapr/gene/` get handled by idr-gallery instead of mapr
- Remove the mapr cache so that we don't get the cached response for these URLs
- For `/mapr/api/[key]/` requests we now response with a 410 response. [EDIT] Now redirects to /searchengine/apidocs/ 302 response - see below.
- Bumps idr-gallery to 3.12.0 to include the 'mapr-redirect' PR above and https://github.com/IDR/idr-gallery/pull/47.
NB: I couldn't see where to add the file I created with:
```sudo vi /usr/share/nginx/html/410.html``` (based on the 50x.html)
```
<!DOCTYPE …
```
> Mapr deprecation

- ansible/requirements.yml
This PR updates the omero_ms_image_region ansible role version
> Update omero_ms_image_region version

- ansible/group_vars/omero-hosts.yml
Just noticed that we don't use the latest render and metadata versions.
> Bump cli render and metadata versions

- ansible/group_vars/omero-hosts.yml
Frances was hoping to get this in the next release. Is it possible to deploy onto idr-next?
cc @dominikl
> Bump iviewer 0.16.0

- ansible/backup_searchengine_data.yml
- ansible/decommission/archive-logs.yml
- ansible/group_vars/searchengine-hosts.yml
- ansible/idr-02-services.yml
- ansible/idr-elasticsearch.yml
- ansible/idr-searchengine.yml
- ansible/openstack-create-publicidr.yml
- ansible/restore_searchengine_data.yml
- scripts/os-idr-snapshot.sh
This PR  contains the required changes to deploy the multi-data source searchengine https://github.com/ome/omero_search_engine/pull/102
> Modify Deployment for multi data source searchengine
